import Head from "next/head";
import useSWR from "swr";
import { useState } from "react";

const fetcher = async (url) => {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  const data = await res.json();
  return data;
};

export default function Home({ initialData }) {
  const [page, setPage] = useState(1);
  const { data } = useSWR(`/api/data?page=${page}`, fetcher, {
    initialData,
    key: `/api/data?page=${page}`,
    /*refreshInterval: 10000,*/
  });

  if (!data) {
    return <div>Loading...</div>;
  }

  const pageCount = data.total / data.per_page;

  return (
    <div>
      <Head>
        <title>SWR example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1> Users Profile</h1>
      <br></br>

      <div>
        <button disabled={page === 1} onClick={() => setPage(page - 1)}>
          Previous
        </button>
        {Array.from({ length: pageCount }).map((_, i) => (
          <button
            key={i}
            disabled={page === i + 1}
            onClick={() => setPage(i + 1)}
          >
            {i + 1}
          </button>
        ))}
        <button disabled={page === pageCount} onClick={() => setPage(page + 1)}>
          Next
        </button>
      </div>
      <br></br>

      {data.data.map((item) => (
        <div key={item.id}>
          <p>
            {item.first_name} {item.last_name}
          </p>
          <img src={item.avatar} />
          <br />
        </div>
      ))}
    </div>
  );
}

export async function getServerSideProps() {
  const data = await fetcher("https://reqres.in/api/users?page=1");
  return { props: { initialData: data } };
}
