import Head from "next/head";
import useSWR from "swr";

const fetcher = async (url) => {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  const data = await res.json();
  return data;
};

export default function Home({ initialData }) {
  console.log(initialData);
  const { data } = useSWR("/api/data", fetcher, { initialData });

  if (!data) {
    return <div>Loading...</div>;
  }
  return (
    <div>
      <Head>
        <title>SWR example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.data.map((item) => (
        <div key={item.id}>
          <p>
            {item.first_name} {item.last_name}
          </p>
          <img src={item.avatar} />
          <br />
        </div>
      ))}
    </div>
  );
}

export async function getServerSideProps() {
  const data = await fetcher("https://reqres.in/api/users");
  return { props: { initialData: data } };
}
